gen_bert: 
	cppt gen_diff \
		--torch_file=./torch/bert-base-uncased/pytorch_model.bin \
		--paddle_file=./paddle/bert-base-uncased/model_state.pdparams \
		--output_file=./paddle/bert-base-uncased/diff.xlsx --auto_match